"""add user_table

Revision ID: 3be0cf06e60d
Revises: 
Create Date: 2018-05-16 08:36:37.679159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3be0cf06e60d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              nullable=False),
                    sa.Column('username', mysql.VARCHAR(length=126),
                              nullable=False),
                    sa.Column('password', mysql.VARCHAR(length=256),
                              nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=126),
                              nullable=False),
                    sa.Column('created_on', mysql.DATETIME(),
                              server_default=sa.text(u'CURRENT_TIMESTAMP'),
                              nullable=True),
                    sa.Column('modified_on', mysql.TIMESTAMP(),
                              server_default=sa.text(
                                  u'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('is_deleted', mysql.TINYINT(display_width=1),
                              server_default=sa.text(u"'0'"),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset=u'latin1',
                    mysql_engine=u'InnoDB'
                    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
